# Task 1

## Importing & Reading files

In [6]:
import os
os.getcwd()
os.chdir('C:/Users/prade/task 1')

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('Mall_Customers.csv')

In [9]:
df.shape

(200, 5)

In [11]:
df.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

## Removing Duplicates

In [13]:
df = df.drop_duplicates()

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   CustomerID              200 non-null    int64 
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64 
 3   Annual Income (k$)      200 non-null    int64 
 4   Spending Score (1-100)  200 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 7.9+ KB


In [16]:
df.nunique()

CustomerID                200
Gender                      2
Age                        51
Annual Income (k$)         64
Spending Score (1-100)     84
dtype: int64

## Checking for missing values

In [17]:
df.isna().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [18]:
X = df.iloc[:,:].values

## Converting categorical values into numerical values

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder1', OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [22]:
print(X)

[[0.0 1.0 1 19 15 39]
 [0.0 1.0 2 21 15 81]
 [1.0 0.0 3 20 16 6]
 ...
 [0.0 1.0 198 32 126 74]
 [0.0 1.0 199 32 137 18]
 [0.0 1.0 200 30 137 83]]
